version: 2.1

commands:
  cached-dependencies:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  install_and_test:
    description: >-
      Install everything required to run the test suite, then run it.
    steps:
      - cached-dependencies
      - run: yarn test.prod

jobs:
  # https://nodejs.org/en/about/releases/
  test_node_lts:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install_and_test

  test_node_latest:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - install_and_test

  release:
    docker:
      - image: cimg/node:12
    steps:
      - checkout
      - run: yarn --ignore-engines
      - run: yarn build
      - run: yarn release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_lts
      - test_node_latest
      - release:
          filters:
            branches:
              only: master
          requires:
            - test_node_lts
            - test_node_latest
